---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: openshift-examples
  name: openshift-examples
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: openshift-examples:latest
  postCommit: {}
  resources: {}
  source:
    git:
      uri: https://github.com/openshift-examples/web.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: ./Containerfile
    type: Docker
  triggers:
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0