apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: openshift-acme
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: openshift-acme
subjects:
- kind: ServiceAccount
  name: openshift-acme
  namespace: production