apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: stage-2-nginx
  namespace: production
spec:
  nodeSelector: {}
  failedBuildsHistoryLimit: 5
  output:
    to:
      kind: ImageStreamTag
      name: 'stage-2-nginx:latest'
  runPolicy: Serial
  source:
    images:
      - as: null
        from:
          kind: ImageStreamTag
          name: 'stage-1-build-static-content:latest'
        paths:
          - destinationDir: .
            sourcePath: /opt/app-root/src/site/.
    type: Image
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.redhat.io/rhel8/nginx-116
      incremental: false
      pullSecret:
        name: 12102058-openshift-examples-pull-secret
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
    - imageChange:
        from:
          kind: ImageStreamTag
          name: 'stage-1-build-static-content:latest'
      type: ImageChange
status: {}