---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production

components:
 - ../../components/openshift-acme

resources:
 - is-stage-1-build-static-content.yaml
 - is-ubi8-s2i-mkdocs.yaml
 - build-stage-1.yaml
 - build-stage-2.yaml
 - deploymentconfig.yaml
 - service.yaml
 - route.yaml